//Comments
// This is the basic of everything.

// Global variables

int glbl_int;
int glbl_lst0, glbl_lst1, glbl_lst2, glbl_lst3;

// Global variables with list & initializers, literals

int glbl_int0 = 0, glbl_int1 = 1;

// Float variables and literals

float glbl_float = 9.99;

// String variables and literals

string glbl_str = "TEST STRING";

// Complex types

pointer int glbl_ptint;

array(10) int glbl_intarr;

pointer array(40) string glbl_ptrstrarr;

array(5) pointer string glbl_arrptrstr;

// functions

int func_a();

int func_c(int a);

int func_b(int param_a, float param_b, string param_c, pointer int param_d);

// main function, supports command line arguments
int main(pointer string args){
    // access op
    glbl_intarr[0] = 1;
    // member op
    // builtin fns
    func_a();
    func_b(1, 0.0, "str", nullptr);
    io.println("Hello World!");
    return 0;
}

// function implementations

int func_a() {
    // Loop Test
    int i = 0, sum = 0;
    while(i < 200){
        if(i == 101) break;
        sum = sum + i;
        if(i == 100) continue;
        i = i + 1;
    }
    return sum;
}

int func_b(int param_a, float param_b, string param_c, pointer int param_d){
    // if clause test
    if(param_a < 0) {
        return -1;
    } else {
        if(param_a == 0){
            return 0;
        }
    }
    return 1;
}
